---
title: "TIDY TUESDAY: OLYMPIAN"
author: "Olaoluwa Gbotoso"
format: html
editor: visual
---

```{r}
# Load the required packages
if(!require("pacman")) install.packages(("pacman"))
pacman::p_load(tidyverse, here, ggthemes, scales, patchwork)
```




```{r}
country_results_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-24/country_results_df.csv')
individual_results_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-24/individual_results_df.csv')          
timeline_df <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-09-24/timeline_df.csv')

write_csv(country_results_df, here("data/country_results_df.csv"))
write_csv(individual_results_df, here("data/individual_results_df.csv"))
write_csv(timeline_df, here("data/timeline_df.csv"))
```




```{r}
# Data exploration
head(country_results_df)
head(individual_results_df)
head(timeline_df)

str(country_results_df)
str(individual_results_df)
str(timeline_df)

summary(country_results_df)
summary(individual_results_df)
summary(timeline_df)
```

```{r}
# Data wrangling

# Dataframe for stacked area chart
timeline_df_long <- timeline_df |> 
                 pivot_longer(cols = c("male_contestant", "female_contestant"),
                              names_to = "gender",
                              values_to = "count")

# Dataframe for line plot
female_proportion_df <- timeline_df |> 
  mutate(female_percent = female_contestant / all_contestant)

# Dataframe for the pyramid plot
timeline_df_long_1990_later <- timeline_df |> 
  filter(year >= 1990) |> 
 pivot_longer(
    cols = c(male_contestant, female_contestant),
    names_to = "gender",
    values_to = "count")|>
  mutate(count = ifelse(gender == "female_contestant", -count, count))

timeline_df_long_1990_later$year <- as.factor(timeline_df_long_1990_later$year)

```

```{r}
# Stacked area plot

area_chart <- timeline_df_long |> 
              ggplot(aes(x = year, y = count, fill = gender)) +
              geom_area(alpha = 0.7) +
              scale_fill_manual(values = c("male_contestant" = "#D95F02", "female_contestant" = "#1B9E77")) +
              labs(subtitle = "Contestants Gender Representation Over Time",
                   x = "Year") +
              theme_tufte() +
              theme(plot.background = element_rect(fill = "#F0F0F0", color = NA),  # Light gray background
                    panel.background = element_rect(fill = "#F0F0F0", color = NA),
                    plot.subtitle = element_text(hjust = 0, size = 12, face = "bold", color = "#323232"),
                    #plot.title = element_text(hjust = 0.5),  # Center the title
                    axis.ticks = element_blank(),
                    axis.title.y = element_blank(),
                    legend.position = "none")
```

```{r}
female_proportion_plot <- female_proportion_df |> 
                            ggplot(aes(x = year, y = female_percent)) +
                            geom_line() +
                            labs(subtitle = "Proportion of Female Contestants over Time",
                                 x = "Year") +
                            theme_tufte() +
                            theme(plot.background = element_rect(fill = "#F0F0F0", color = NA),  
                            panel.background = element_rect(fill = "#F0F0F0", color = NA),
                            plot.subtitle = element_text(hjust = 0, 
                                                         size = 12, 
                                                         face = "bold", 
                                                         color = "#323232"),
                            #plot.title = element_text(hjust = 0.5),  # Center the title
                            axis.ticks = element_blank(),
                            axis.title.y = element_blank())
```

```{r}
# Pyramid plot
pyramid_plot <- timeline_df_long_1990_later |> 
                ggplot(aes(x = year, y = count, fill = gender)) +   # Fill column
                geom_bar(stat = "identity", width = 0.9) +   # draw the bars
                # Adding labels outside the bars
                geom_text(aes(label = comma(abs(count))),
                position = position_nudge(y = ifelse(                                                                                                           timeline_df_long_1990_later$gender == "female_contestant",                                                    -50, 50)),
                           size = 3.6, 
                           hjust = ifelse(timeline_df_long_1990_later$gender == "female_contestant", 1, 0)) +
                # Adding a year label next to the bars
                geom_text(aes(y = -400, label = year), # Position year next to the bars
                          size = 3.6, 
                          hjust = 0.5, 
                          vjust = 0) +
                scale_y_continuous(breaks = c(-100, 0, 600), 
                                   labels = abs, 
                                   limits = c(-1200, 1600)) +  # Labels
                coord_flip() +
                labs(subtitle = "Contestants by Gender from Year 1990",
                     fill = "Gender") +
                theme_tufte() +  
                theme(plot.background = element_rect(fill = "#F0F0F0", color = NA),  
                      panel.background = element_rect(fill = "#F0F0F0", color = NA),
                      plot.subtitle = element_text(hjust = 0.5, size = 12, face = "bold", color = "#323232"),
                axis.ticks = element_blank(),
                axis.text.y = element_blank(),
                axis.title.y = element_blank(),  # Remove x-axis title
                axis.title.x = element_blank(),  # Remove x-axis title
                axis.text.x.bottom = element_text(vjust = 1),
                legend.position = c(0.8, 0.5)) +  
                scale_fill_manual(values = c("#1B9E77", "#D95F02"),
                                  labels = c("Female", "Male"))




```

```{r}
# Combine the three plots 
combined_plot <- pyramid_plot + female_proportion_plot / area_chart + plot_layout(ncol = 2, widths = c(2, 1)) +
  plot_annotation(title = "Trends in Gender Distribution of IMO Contestants", 
  caption = "Tidytuesday week 39 | Graphic by Olaoluwa Gbotoso"
) & theme(plot.title = element_text(size = 20, hjust = 0.5),
          plot.caption = element_text(size = 14),
          plot.background = element_rect(fill = "#F0F0F0", color = NA))

# Display combined plot
combined_plot

# Save plot with larger dimensions
ggsave(here("image/combined_plot1.png"), width = 12, height = 8)  # Customize width and height
```
